In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
import joblib

In [2]:
df = pd.read_csv("./Advertising.csv")
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [3]:
X = df.drop("sales", axis=1)
y = df.sales

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=36)
for i in [X_train, y_train, X_test, y_test]:
    print(len(i))

140
140
60
60


In [6]:
model = RandomForestRegressor(n_estimators=100, random_state=36)
model.fit(X_train,y_train)

RandomForestRegressor(random_state=36)

In [7]:
model.score(X_train,y_train)

0.996345334891328

In [8]:
y_pred = model.predict(X_test)

In [9]:
s1=pd.Series(data=y_pred, index=X_test.index)
s1

106     7.333
52     21.141
92     18.764
184    16.433
97     15.099
155     3.375
198    25.034
85     15.014
143    10.203
61     24.633
14     18.323
77     13.616
10      9.282
58     23.146
156    14.707
75      8.552
56      6.262
139    21.050
53     20.635
74     17.149
110    12.619
28     19.228
16     12.337
119     6.988
73     11.153
197    12.791
195     8.547
123    14.363
194    16.250
116    13.235
169    13.524
8       5.360
102    13.285
152    16.589
80     11.736
65     10.026
50     11.533
146    12.392
63     12.556
51     10.325
48     15.719
27     15.585
163    17.875
131    11.672
192     6.901
71     11.747
149    10.017
179    12.751
78      5.697
136     8.012
6      10.949
57     13.535
114    13.174
172     7.207
89     15.937
186    10.446
35     12.045
4      13.109
125    10.169
19     14.861
dtype: float64

In [10]:
y_pred2 = model.predict(X_train)
y_pred2

array([10.391, 17.493,  8.626,  5.682,  9.92 , 15.351, 12.748, 10.662,
       22.212, 19.126, 11.535, 20.712, 18.181,  9.837, 16.794, 11.145,
        6.849,  8.   , 11.448,  8.794, 24.049, 15.263, 10.106, 21.455,
       10.915, 18.973, 11.851,  9.524,  9.787, 18.479,  7.126, 20.447,
       21.828, 14.865, 11.498,  3.554, 17.461,  8.878, 10.234,  6.799,
       22.956, 11.967,  8.972, 11.884, 16.35 , 15.591, 10.599, 11.71 ,
       13.124, 22.23 , 20.166, 15.092, 15.514, 19.259, 20.215, 22.069,
       22.393, 11.043, 24.09 , 10.417, 16.017, 11.621, 15.443, 19.368,
        7.168,  5.918, 23.12 , 11.899,  9.725, 21.947, 11.098, 26.321,
       22.444,  8.818, 17.197, 11.639, 18.285,  9.659, 23.402, 15.509,
       11.651, 12.671,  8.308, 13.046, 12.849, 16.122, 14.377,  8.735,
        9.626,  8.513,  5.618, 18.507, 11.012, 14.632, 14.498, 15.296,
       12.166, 12.138, 25.345, 10.972, 11.187, 11.424, 12.843,  8.952,
       24.834, 14.791, 12.103,  9.266,  9.647, 13.295, 11.965, 17.085,
      

In [11]:
s2 = pd.Series(data=y_pred2, index=X_train.index)
pred = pd.concat([s1,s2], axis=0)
pred

106     7.333
52     21.141
92     18.764
184    16.433
97     15.099
        ...  
161    13.122
168    17.015
158     7.075
98     25.222
133    19.621
Length: 200, dtype: float64

In [12]:
df['pred'] = pred
df.head(10)

TV  radio  newspaper  sales    pred
0  230.1   37.8       69.2   22.1  21.947
1   44.5   39.3       45.1   10.4  10.715
2   17.2   45.9       69.3    9.3   8.626
3  151.5   41.3       58.5   18.5  18.181
4  180.8   10.8       58.4   12.9  13.109
5    8.7   48.9       75.0    7.2   7.126
6   57.5   32.8       23.5   11.8  10.949
7  120.2   19.6       11.6   13.2  12.748
8    8.6    2.1        1.0    4.8   5.360
9  199.8    2.6       21.2   10.6  11.098

In [13]:
df['dif2'] = (df["sales"]-df["pred"]).apply(lambda x: abs(x))
df.sample(10)

TV  radio  newspaper  sales    pred   dif2
142  220.5   33.2       37.9   20.1  19.819  0.281
159  131.7   18.4       34.6   12.9  13.124  0.224
114   78.2   46.8       34.5   14.6  13.174  1.426
38    43.1   26.7       35.1   10.1  10.106  0.006
136   25.6   39.0        9.3    9.5   8.012  1.488
140   73.4   17.0       12.9   10.9  11.043  0.143
23   228.3   16.9       26.2   15.5  15.514  0.014
163  163.5   36.8        7.4   18.0  17.875  0.125
71   109.8   14.3       31.7   12.4  11.747  0.653
12    23.8   35.1       65.9    9.2   8.878  0.322

In [14]:
df['dif2'].mean()

0.3312249999999996

In [15]:
model.score(X_test, y_test)

0.9785603141332715

In [16]:
joblib.dump(model,open("model2.pkl","wb"))

In [17]:
loaded_model = joblib.load(open("model2.pkl","rb"))

In [18]:
import numpy as np

In [19]:
data =[
    {"TV":230, "radio":37.8, "newspaper":69.2},
    {"TV":230, "radio":37.8, "newspaper":69.2}
]
data = pd.DataFrame(data)
print(data)
loaded_model.predict(data)

    TV  radio  newspaper
0  230   37.8       69.2
1  230   37.8       69.2


array([21.947, 21.947])

In [20]:
loaded_model.predict([
    ["59.6",    "12.0",     "43.1"],
    ["0.7",     "39.6",     "8.7"],
    ["230",     "37.8",     "69.2"]
    ])

array([ 9.659,  3.554, 21.947])

In [21]:
df[df.sales == df.sales.max()]

TV  radio  newspaper  sales    pred   dif2
175  276.9   48.9       41.8   27.0  26.321  0.679